### ISSUE TITLE
What is the expected factorio root folder?

### ISSUE THREAD

**Issue by jtv199** [Tantrisse/Factorio-mods-manager#12]
The steam factorio install folder `f/SteamLibrary/steamapps/common/Factorio` does not have a mod folder inside it and the folder inside users `c/Users/HighOrder/AppData/Roaming/Factorio` does have an automatically generated mods folder, yet it doesn't have a bin folder which the script seems to expect. Perhpas this is not compatible with windows?

**Comment by Tantrisse** [comment]
Hey, this helper is meant to be used with the Headless Linux version (server without GUI).
It seems you are trying to use it on a non headless version Windows version, which is not supported.

Have a great day,
Tantrisse
