### ISSUE TITLE
Unable to load mod with spaces in url

### ISSUE THREAD

**Issue by ZeroOne010101** [Tantrisse/Factorio-mods-manager#14]
It seems the manager is unable to load mods with spaces in the url.
Concrete Example: https://mods.factorio.com/mod/Flow%20Control
### Command:
`sudo -u factorio factorio mod install Flow Control`
### Result:
```
Couldn't load config file, as it didn't exist. Continuing with defaults anyway.
Error getting mod "Control" infos. Ignoring this mod, please, check your "mod-list.json" file.
```
### Resolution:
Note workaround in README.md.
I was able to make it Work by using this command:
`sudo -u factorio factorio mod install Flow%20Control`

### Notes:
I use factorio-init, hence the commands.
The issue seems caused by firefox.
Firefox applies url-encoding when copying the entire url, but leaves the space if you only copy the last part (which is the only part actually needed).

**Comment by Tantrisse** [comment]
Hi, I added a section on the readme on how to prevent problem when the mod name contains spaces : https://github.com/Tantrisse/Factorio-mods-manager#a-note-on-mod-names-containing-spaces

Thank you for reporting the problem, I didn't even know there could be mod with spaces in the name key ^^

Cheers,
Tantrisse
