### ISSUE TITLE
missing config file causes failure

### ISSUE THREAD

**Issue by idprism** [Tantrisse/Factorio-mods-manager#4]
I seem to be having an issue with not having a config file.

This will happen if the config.json is not present, even if all required cli options are present.

Copying the config.example.json to config.json removes the error, even without editing the file.

```
python3 /opt/factorio-mods-manager/mods_manager.py --p /opt/factorio --list -v
Couldn't load config file, as it didn't exist. Continuing with defaults anyway.
Traceback (most recent call last):
  File "/opt/factorio-mods-manager/mods_manager.py", line 450, in <module>
    sys.exit(main())
  File "/opt/factorio-mods-manager/mods_manager.py", line 414, in main
    display_mods_list(read_mods_list())
  File "/opt/factorio-mods-manager/mods_manager.py", line 104, in read_mods_list
    with open(glob['mods_list_path'], 'r') as fd:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

So, either an explicit requirement for config.json file should be stated in README, or file should be optional if cli required parameters are set.

Thanks!

**Comment by Tantrisse** [comment]
Hi,
I just pushed a fix, there should be no more problem about running without config file.

Cheer.
