### ISSUE TITLE
Depndencies install seems broken

### ISSUE THREAD

**Issue by Ash-oi** [Tantrisse/Factorio-mods-manager#6]
https://github.com/Tantrisse/Factorio-mods-manager/blob/b1facbf541bdf21d4967a0e68938c6b2dd91f2b0/mods_manager.py#L185

for whatever reason `mod['name']` is appending `(?)` to the start of each mod name so the URLs are broken, putting `print(request_url)` on the next line is turning up stuff like `https://mods.factorio.com/api/mods/(?)aai-industry/full
` which 404's

**Comment by Tantrisse** [comment]
Hi,
I just pushed an update which fix how dependencies are detected and installed.

The weird case of `(?)` dependencies is now totally ignored as these are "hidden" optional dependencies which should not be installed, they are listed by the mod just to influence the order of loading if both mods are installed.

Cheers.
