### ISSUE TITLE
Manager can't find GLIBC

### ISSUE THREAD

**Issue by TheSilasm8** [Tantrisse/Factorio-mods-manager#9]
I'm using Factorio-init to call the mod install function in this manager and it's not able to find the GLIBC version installed in Ubuntu 20.04. I have GLIBC 2.31-0 installed and factorio is able to run just fine. I found the glibc location in /lib/x86_64-linux-gnu, but setting the alternative directory to that doesn't seem to work. So I tried clearing the alternative directory and it also gives me an error:

```
user@server:/opt/Factorio-mods-manager$ factorio mod install Squeak%20Through
usage: mods_manager.py [-h] [-v] [-d] [--downgrade] [-p FACTORIO_PATH] [-u USERNAME] [-t TOKEN] [-l] [-i MOD_NAME_TO_INSTALL] [-U] [-e] [-r REMOVE_MOD_NAME]
                       [-E ENABLE_MODS_NAME] [-D DISABLE_MODS_NAME] [--reload] [-s SERVICE_NAME] [-nrd] [-nrrd] [-iod] [-rod] [-icd]
                       [--alternative-glibc-directory ALT_GLIBC_DIR] [--alternative-glibc-version ALT_GLIBC_VERSION] [--update-mod-manager]
mods_manager.py: error: The directory "" for the alternative GLIBC library points to nothing !
```

I also tried to install GLIBC 2.18, but I'm running into issues. It may be that [the instructions](https://forums.factorio.com/viewtopic.php?t=54654#p324493) are written for CentOS and I'm using ubuntu. I'm still new to linux, so I'm not familiar with the commands and equivalents.

Is there a way to update the script to use newer versions of GLIBC?

**Comment by Tantrisse** [comment]
Hi, humm it seems that there is no error here, just a misconfiguration :/

The problem (I think) is that you have the key "alternative_glibc_directory" in your `config.json` set to `""`. If you don't want to use an alternative GLIBC version and use the default system version, you just have to remove the 2 keys `alternative_glibc_directory` and `alternative_glibc_version` from the `config.json`.

But, this is not your fault, I should (and will) reword the readme a bit !
Maybe I'll rework a bit how these params behave and should be set...

Tell me if removing the keys fix your problem !

**Comment by TheSilasm8** [comment]
Ah I see. Removing that does seem to fix the issue. Thanks!
